name: Deploy and Restart

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Stash local changes
      run: git stash

    - name: Pull latest changes
      run: git pull origin master

    - name: Apply stashed changes
      run: git stash pop

    - name: Restart Docker Compose
      env:
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
      run: |
        docker-compose down
        docker-compose up -d
